# Generated by Django 4.0.2 on 2022-04-28 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='user',
            new_name='user_id',
        ),
    ]
