# Generated by Django 4.0.2 on 2022-05-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_user_id_auction_user_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='image',
            field=models.ImageField(blank=True, default='/static/images/placeholder-1.png', upload_to='images', verbose_name='lot image'),
        ),
    ]
